### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by marco-zanon** [lucaslrc/web-scraping#2]
Oi Lucas, desculpa te contactar por aqui, procurei seu email e não encontrei...
Meu nome é Marco Antonio Zanon, trabalho na área de análise de dados do Tribunal de Contas do Estado de São Paulo, e uso o pacote google-search do rocketlaunchr no meu trabalho.
Vi que vc fez um fork do referido pacote e tenho algumas dúvidas (de novato) a respeito dele.
Haveria possibilidade de vc disponibilizar aqui um email de contato para que eu pudesse tirar essas dúvidas?

Abs e obrigado desde já,
Marco Antonio Zanon

**Comment by olucaslrc** [comment]
Opa Marco, vai lá no meu perfil do GitHub, lá você vai encontrar o meu twitter, é só mandar uma mensagem por lá. Valeu!
